hash-format = "sha256"

[[files]]
file = "config/byg/README.txt"
hash = "716925cf1fd06d3d981aac5adbdc7a84dae30dbb64b17b0c25a8f739be01883d"

[[files]]
file = "config/byg/biomepedia.json5"
hash = "d9b7c4d1b5445c9b34618918f94f190e2f9dd5312ae1e241e11ac796edf7e31c"

[[files]]
file = "config/byg/client/biomepedia_inventory.json5"
hash = "a5e9cbd9ce3331dfad0c79129d7a38fbc724806549da3087b866f784966f4c33"

[[files]]
file = "config/byg/config_versions.json5"
hash = "b7145901f650508f5c188bfb2069779beb32a46fc30679a33e9fb95ec686050f"

[[files]]
file = "config/byg/settings.json5"
hash = "c60d4e23d3d8a9c84b97b54a35d02fd822ee7b2d7ce10f45b9daa6185013f4cb"

[[files]]
file = "config/byg/surface_rules/end_surface_rules.json5"
hash = "3515ed2d93cf2664da9548beb6871e9f059ff2fcc2d42c52e7aa84307dafc2b2"

[[files]]
file = "config/byg/surface_rules/nether_surface_rules.json5"
hash = "1c2e8e069f5b766411dabbe843d0fc905ad94785eaa111a56806e8f96c692461"

[[files]]
file = "config/byg/surface_rules/overworld_surface_rules.json5"
hash = "bfc984d665a724ec097a16745db6be175550c3727bafee373fa73d6a07132e63"

[[files]]
file = "config/byg/trades.json5"
hash = "f0c7398837fd982ae6478afc4d0a7d114a3d900f6e212fd4bd0403b541e5f505"

[[files]]
file = "config/citresewn.json"
hash = "dcb9f9dd8184ba8ee7c81e785f677434c7cda2acb925fd3d542e2a361ee78e32"

[[files]]
file = "config/debugify.json"
hash = "e42d605709dbede0b7db4b3392a12c851d572398af021e285e02e3499bca8b7b"

[[files]]
file = "config/defaultoptions/options.txt"
hash = "ec967fb3a0371b6fd65721916bcf32b22cf342d6c347ca94814a31820ddd0e1a"

[[files]]
file = "config/extraalchemy.json"
hash = "dfb83443bfd42d62bab93691a7d04c727bb06bdf12f1ed90577b85a963088c02"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "537b713a81cdf61b7f9b89e351beb01fed73c50331a28a9fbead59289d1a9d1e"

[[files]]
file = "config/forgivingvoid.toml"
hash = "f32cf74e933ec448906a0e1f58af57117b9bdfc0390cb69d733dc9a560db2ef5"

[[files]]
file = "config/global_data_and_resourcepacks.toml"
hash = "3a2a810a45163f5e9403176263d532f8d6151590a5ce65ae122fb5f0cac724fa"

[[files]]
file = "config/immersive_portals_fabric.json"
hash = "6eda605ff87de9e42fee0f43f507e0153a55921d7be613d35c3aa1c943ad177b"

[[files]]
file = "config/modmenu.json"
hash = "b2d6f97d6f09d3c02504264a778ab1958378c91e5d743afed9ab71846073bf60"

[[files]]
file = "config/numismatic-overhaul.json5"
hash = "fa01f83a5d52b00f3d0dbe324631e9be95fb29e6ddb24e16fc71a06a48666628"

[[files]]
file = "config/puzzle.json"
hash = "1db967817059276c90dd3fd34e2573abe7883f2a169285a2c03632f6c9d31fe8"

[[files]]
file = "config/slightguimodifications/config.json5"
hash = "a8b17931af43862e6acca2cee3e23fc29e06a6bf0cfd41f26f6b24201bfb5479"

[[files]]
file = "config/slightguimodifications/cts.groovy"
hash = "d081654f53ee87db599754a20bf0baec1be0650ffbd24240bef0529dc09525c2"

[[files]]
file = "config/sodium-extra-options.json"
hash = "6536c58c5a0d949fb5a37a771f69b49ff415bf50d591dc54190fc601522afb4a"

[[files]]
file = "config/waystones.toml"
hash = "6e29e151af147877bd45724ff7f53cf1ba76fec96ad3a35c589293ddded86542"

[[files]]
file = "config/yosbr/config/bobby.conf"
hash = "7668a9ed5d5d6878dd49d552396b7aab57e5345d031a0f776b90f9a477a06195"

[[files]]
file = "config/yosbr/config/borderlessmining.json"
hash = "1dfdc3360afe91b5804eef79f8b868f874e3dfc0c975495f8994f378ffe37a8f"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "8f5c4bac35757d624f296419976aff70a4a5b95c4430aff06048013ea7dd25c4"

[[files]]
file = "config/yosbr/config/cem.conf"
hash = "51519ddcc6823cbe1f22b8977fe103eb8c01b1872899634ddc06814f3ef2da9b"

[[files]]
file = "config/yosbr/config/dynamicfps.toml"
hash = "00adc4f855ed41412f3c3eb48b859c4ae68b5f2c30ba4c332e66f38e79a0c449"

[[files]]
file = "config/yosbr/config/entity_texture_features.json"
hash = "35cb31f6ae8e293fed8e4eb5dff841c1e913ca2342af5fd47296f31024e14950"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "3f5878535aacbfea79ae6da2f9142963f5662af3141692f0ba945767c9096ce5"

[[files]]
file = "config/yosbr/config/lambdabettergrass.toml"
hash = "a96351b4d852862f0c994cd61a05856c965e73e8f698591f0f2f5ba9a30bd952"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "5b83dbf79c2df634529371bb6fe139fadaf485710212080363a522f2f5983ca6"

[[files]]
file = "config/yosbr/config/midnightcontrols.json"
hash = "b792f2977c2889e388d0a0e83e316ed4f27050729d86c8623e8472accb8a2a46"

[[files]]
file = "config/yosbr/config/midnightlib.json"
hash = "f7f7122784c7a6bcdb034e663fd756e16ffe69a668cb1b334e2be622f8c7bd55"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "dd6f94bc9b0002d8db083a1f7a4238fd93489046f3084b03ce92338ab5a65b00"

[[files]]
file = "config/yosbr/config/zoomify.json"
hash = "cc6f863a8e250641184bfcd3b59169491fe5414a036996401b66bc019ebeedd8"

[[files]]
file = "config/yosbr/options.txt"
hash = "69305f9d9e0c54cc866cd9d3a381f14532e3be6b9b00a80707c19517e6a0874b"

[[files]]
file = "datapacks/TerraProxy.zip"
hash = "a25251bd33f5c47a3fe7abb510726dd5405c52467c6e34fa6bf89d61d86a7f0b"

[[files]]
file = "datapacks/Towers_Of_The_Wild_Reworked_v3.0.0_Waystones.zip"
hash = "3ca8d576e3f116a3cebb005527caf53b07125ea031cb8c58445bea129b7b9459"

[[files]]
file = "mods/advancementinfo.pw.toml"
hash = "a0331c538ab9a55bd911259fea52810f120732d5c44d6073d2e52ae0b1e5ea6b"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "9b372af0015aba3f61b7d41ceeb81cea5701763d6da6ad1448695b56f73c14e8"
metafile = true

[[files]]
file = "mods/antighost.pw.toml"
hash = "4867873d4e8d67728d599b6b8971556cb3e163e7e601c6da5f2a8ec8d021afc7"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "3b39d3a2bea559be8777c65db90a2f15377d6656e17cbc3400be746c5ec0ebc0"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "462df058fcbca113feb8a65eed8ef761dd19eeea330480e758728a49c57f4e54"
metafile = true

[[files]]
file = "mods/bettermounthud.pw.toml"
hash = "7d97c92ccaef638689651372262af9d8e69532ab4a5025cddf3f5e9ee948bf77"
metafile = true

[[files]]
file = "mods/biomesyougo.pw.toml"
hash = "ee9eff41327993190f1ecc723c1b7985c3ebc3627ae726a339cac6ebec6eb009"
metafile = true

[[files]]
file = "mods/borderlessmining.pw.toml"
hash = "486877dab9660684501cbf535c5de3069ce2ea2e7e7868edfbc78ec3a9875f8b"
metafile = true

[[files]]
file = "mods/campanion.pw.toml"
hash = "8d3de765ffa83b0499e328dbd1827e35c2a9f88c11cdc09ba1f4efe7d68f531f"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "3861994eced5388522a99c6f6e445a4b88719c10855b65ac32b0692b01eab80a"
metafile = true

[[files]]
file = "mods/cem.pw.toml"
hash = "4a8db6f937d289f7802478e8b7b0e682cec4bf5a5ed51aef7e0e25346e3b1f61"
metafile = true

[[files]]
file = "mods/citresewn.pw.toml"
hash = "c4310c07b4c226fa496670126abf919f7ad3ca4d7e541e298d46275db55c6b5d"
metafile = true

[[files]]
file = "mods/cloth-api.pw.toml"
hash = "66e5a832549ae569bb7ccffecbc888aa0b56abdd06bc98f7fd027069738d04d0"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "77bd9b9ae2bf78481ba939cc78e5e4c0d9528516aa791305eecb39eb56e13125"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "5af92ecf72483d4b2c2fdb558686a6276249e8d7d8c5c46b96b851f16c1d962a"
metafile = true

[[files]]
file = "mods/colormatic.pw.toml"
hash = "71522a73a6a7384ebbf4a603bd237c41b004cfb1f3213694d236307673eee48a"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "9093b643267995dc21f7cb3cfff0ed9063587691caba8eed7d5972ed6e42f7de"
metafile = true

[[files]]
file = "mods/cristel-lib.pw.toml"
hash = "743cf8a82c1e9b2abaa693d5d7add040020f7aa1689671ae948630c4dce622c4"
metafile = true

[[files]]
file = "mods/cull-less-leaves.pw.toml"
hash = "d277acad312315e8700c4ed59553f39ec175d5882cd3b94fa235eace0a862f55"
metafile = true

[[files]]
file = "mods/dawn.pw.toml"
hash = "b60fc5c154d6ca0e07406638d53bfbaa751e3ef517ff553fcec8543847844728"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "38a6671631add34eac47d2c2cc1bb480e5479d15548f10b0eaaafe200dfd5a37"
metafile = true

[[files]]
file = "mods/default-options.pw.toml"
hash = "77d4f4d154c64e82ca5151ea8c8b610ab9ffb31c93a51b84230a7f4162d20313"
metafile = true

[[files]]
file = "mods/dont-clear-chat-history.pw.toml"
hash = "d6b3fea370a85afbc4b829eacd9492bfa70bae6fe7680ab22c66244fa67362f1"
metafile = true

[[files]]
file = "mods/drp-global-datapack.pw.toml"
hash = "5e6d7951a08c552cacd6c38a7501d48b5be0b68750d2e601aa8008194deeb09f"
metafile = true

[[files]]
file = "mods/dynamicfps.pw.toml"
hash = "8d7f7d58c14a5c83ef0ccb1c468939ad223765122b71de888a8f7a020dbf40bf"
metafile = true

[[files]]
file = "mods/enhancedblockentities.pw.toml"
hash = "6ae1c24c46bfd4e641f88617852962b90baf7827efc5094c2ea9ffa62ed68b48"
metafile = true

[[files]]
file = "mods/entity_texture_features.pw.toml"
hash = "0760c1a3ec88148fe117894bc7e65b550d3b95950bea2f51690d9ca16ce9bdb3"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "af7557b39a8a5d3eaa0d07e9cee235fb0ba02e5ce8e96c5a4566ab24183eda0c"
metafile = true

[[files]]
file = "mods/extraalchemy.pw.toml"
hash = "0275babee44e40b37c2425bd6f793e459bfccd8ebb1da9dc17bdf5363764fee2"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "268eee36d007dc55ff7abb4e4eff3dc2d6d8007fad18bea53330dffffeee41f5"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "7be1e122e9ef8f1b7f2df9ffccf02cf83a52d0a53ae5ba7d07ea7bd3cc149101"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "fee47049fb1514eaa778a220f54dca753a9cef826d9933b08799fbaccb49d672"
metafile = true

[[files]]
file = "mods/farmers-delight-fabric.pw.toml"
hash = "f5a63f7098aff652010fbf06a7cb93ff042fb59345a2b2255f03063499c5951e"
metafile = true

[[files]]
file = "mods/farsight-fabric.pw.toml"
hash = "5a7acafa82dd65637a857bbf088df84954daf9dab936f8c5f376e45a35b0f189"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "dadd545ffe62ebe3ced0d7da56ffa549f1a1643eaf91124f9fdb700e85bf45a9"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "d3caf0b1837490d2b0169fa8e0ff485158c70200c23dbdefead7912d47e5fc70"
metafile = true

[[files]]
file = "mods/forgiving-void.pw.toml"
hash = "6f84734cbe6b13a55083e7608bfc5773d89b620810cb65b7e570b6c94edebd05"
metafile = true

[[files]]
file = "mods/ftb-library-fabric.pw.toml"
hash = "91136fa2e69d33b38212fd767d4f60a58c018e217b2cf5b3d4f136396124b08b"
metafile = true

[[files]]
file = "mods/ftb-quests-fabric.pw.toml"
hash = "09b05de422ce7d92532b1bb1e72c1a054e6a476d04d671684e3adab8d69e64af"
metafile = true

[[files]]
file = "mods/ftb-teams-fabric.pw.toml"
hash = "df222a476c046b30bc6d97327fdfcc80d1412e3fb3032a648b0709f580dce8bd"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "ecdc6da68522e33a1084b9fd81cfe38bd69de178bb6668899764e4a7ac115d13"
metafile = true

[[files]]
file = "mods/huge-structure-blocks.pw.toml"
hash = "cdf95e227083b15739cbef5632ad685cdbf791e08a37dc8c63c3d0cab9f785d1"
metafile = true

[[files]]
file = "mods/immersiveportals.pw.toml"
hash = "0a0914edef91de5cf50bd1a97d9d4a7814c98c376a36264b5d250d8618c7bd4a"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "b3b62810b79ffaac2b9c935655109766e382400a6db1625cfffc1e97eab039fd"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "689beb7c10f85f12f08d2b5198e02c8ef72bf3a5372e390d76c7412cbc807296"
metafile = true

[[files]]
file = "mods/isxander-main-menu-credits.pw.toml"
hash = "bf619ec7dae9e2dcd694424a7c702c7fa1f549c3589f9ea0f4ef4d40d9041c2a"
metafile = true

[[files]]
file = "mods/item-filters.pw.toml"
hash = "3fd6c3023e220fe708024d6151ee74f0f86589e75e1214daaf39ddb82d7b9e5e"
metafile = true

[[files]]
file = "mods/itemmodelfix.pw.toml"
hash = "79c587b5c7af67f29fba45cdd93a5e5de3a050ede5976ec7d19ed9101c2231c3"
metafile = true

[[files]]
file = "mods/just-mob-heads.pw.toml"
hash = "6bf7007d821ad2eb9f5db9b4ad456e6d66f3b24ddb0a022041f6cc2a561b06fb"
metafile = true

[[files]]
file = "mods/lambdabettergrass.pw.toml"
hash = "de58df0f027d717b78686db85c799e9d40f4e98424a6ae0bf42c1c949a68b042"
metafile = true

[[files]]
file = "mods/lambdynlights.pw.toml"
hash = "48e6915450b575a56df57de63b16f9bfad288adb89a2c43cf87f875377fb4762"
metafile = true

[[files]]
file = "mods/languagereload.pw.toml"
hash = "ae860e2d21718e20bfefce518b4930987504ab7b58db5d7ed90663f68d44250b"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "7afa8c84512137ca4abe89199feeccac1554d02bd83c5e011c052eef3c4448a3"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "96b41235a3747da67a517a2ef5104c5298d258a0663d18f947eecaf8e63c7084"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "868f100a2b5e3e47724ecf0174364bd44193b51e40c70b9c59a85dcf8aec66b1"
metafile = true

[[files]]
file = "mods/midnightcontrols.pw.toml"
hash = "7919045edb833eb4636f1b88d9ceaf478945440bd6e3a9d6e674d50425c7d601"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "0a8e6a58962ba40f696a44cb2d02355490bc831b49509f8083e3e7bc89b40052"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "c35b0f5550fca7c9697b04a8dce969f492923f2d6a67cb4bc89aa81761e684f1"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "e0190ea04424f2da3ed3e2a262f3f8596e48275109c5401e590690fd599ae1a8"
metafile = true

[[files]]
file = "mods/naturalist.pw.toml"
hash = "a5653a473c2ded9dd727d677f576194386884905a600336dbeea7eb6cb7049e2"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "030b818f7aa75596fe5c0a04b15c66dc0531c79aee5820a30379cc5af77ee46d"
metafile = true

[[files]]
file = "mods/no-fade.pw.toml"
hash = "da5bc04ce1665f78ceae93794202796d2041d6274ffdcfa227bf9e3024ca5ea3"
metafile = true

[[files]]
file = "mods/numismatic-overhaul.pw.toml"
hash = "a115a703ac767250970be74009834f37e796e9d0e65caa47a12a75c34d903c61"
metafile = true

[[files]]
file = "mods/open-parties-and-claims.pw.toml"
hash = "24d9155e0b2c610e9531767671c65e020e00bf94ad0698094892f794120a676c"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "13be07b6931766db4c96bcda66ed9d2aee539b451e142dc84932ccab21438020"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "51ea57345c9369d53fd17ca8663f43f587d3bee6765a0afdf43ab7955d94eca2"
metafile = true

[[files]]
file = "mods/pehkui.pw.toml"
hash = "8475894e2eeeaef0b12f4209b7c6da565d2d23b866437f23c70361160af17114"
metafile = true

[[files]]
file = "mods/persona.pw.toml"
hash = "b6b722c4f476be297928c584e44d416954e3b3ae0fc674963d1b7c7c1d16cb8d"
metafile = true

[[files]]
file = "mods/player-roles.pw.toml"
hash = "06a7372d48a3a24d7cbf9c58dee9455a3547bc44271e229b1a9e21f720145b85"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
hash = "da9464131cbeaabcfd1fb5bd3b4361de7e406f50904efa0e79c70b0beff08d8f"
metafile = true

[[files]]
file = "mods/promenade.pw.toml"
hash = "90c566f04f86546c14ac20a35e45c593a623b862d26e70ad64f3568b3029acb1"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "a88a9e195060716db1697f4b651acd71ce2e25a49c9ed0f59d74394803386f53"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "94a09aed86bebfe5339b71325b1c1555418f5f83c2412f9537d429dcf8a96adc"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "54d7c9de091ab3d57aa692a473a70e7575a33eaac0baa347e0b74f6d959d148d"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "9b1fba2f0b96e6c25d7c48e4f5635c263c06f0c2b42e76bccd96b5f2120b9bed"
metafile = true

[[files]]
file = "mods/slight-gui-modifications.pw.toml"
hash = "6712f720696377f5e8340ce1db3b636fdcf0ae01f85016f9d81b4e9f12552151"
metafile = true

[[files]]
file = "mods/smoothboot.pw.toml"
hash = "0d70acdcbabace61b1c8a3dca7be2b6a83705c66cdca88c51a89158746e86fda"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "57a8156ca507aef595456aede3dc9f8ad5b9e9e835900c22f9817b79be1202e8"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "53eee6a4ef1a3ae38ef86e785dbc83219de9630590594797c133a720f8bed6ee"
metafile = true

[[files]]
file = "mods/spawn-world-setter.pw.toml"
hash = "b6a20e0bde66a0f8a930fa337423c3753ed31d4fcbd6300f87c08179317b89b8"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "0bdd006a7944fecd72f14fb94df21a2d80a7b45eac633c32ec5c5af7a57dd701"
metafile = true

[[files]]
file = "mods/styled-nicknames.pw.toml"
hash = "cd8ce0429f1d4bb4c4ef4fd09a831955da0c4e1310d607bfbe6480fd11866b52"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "464efd679154b3d311531b55d0bba57568a4bd6066f03b930635a308d7e3547b"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "535ddd4654d0cf6d47ddd759d98a60276f6c4aa267f1f4a38715c3f7671f557b"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
hash = "81d5be64d5211afe8f54c104805a5d62cd0e0a7637aa7ec68aadb47522a68286"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "49f5590e6160266691eaca6948b33a3a2763e590ed4bcf90189f13650066c84e"
metafile = true

[[files]]
file = "mods/unfixed-seeds.pw.toml"
hash = "1ac4efbfb3aaa92fcc345081c3e90267be4db1a7566c02755399cb8fb5d7d5c6"
metafile = true

[[files]]
file = "mods/universal-graves.pw.toml"
hash = "0c006409062946ef5d40bbfa4232f01bd7a84690ed274810ebb3c618a184b2fb"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "1438d84a1f53c60f1f95c104d44e361c9af6e05acd0a81ce7a90c57ad1f2d061"
metafile = true

[[files]]
file = "mods/worldborderfix.pw.toml"
hash = "e8477dedbcb2beed03d7f10626413e6284a1c468b42cccffa85dff8d8ea985d0"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "9cba8becd46d571b7576be0d34fea48a7c38f5745265186c7baf1c79251ef373"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "999897520d368b789eff65ad572200ba6c703a38c6bc732399bc0c8e4d1c470c"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "1de78bba80808876a9510980b35a956a57a553bd841fc9db07edbd1bcef95e3b"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "9dffabf569e9e1b272c7311579a4a758a88e551bf2b2c1d75319489656053c55"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "7146d48eb92134c864fa003f8019527887fbd09aa47b3f43a9164859e27a34fc"
metafile = true

[[files]]
file = "options.txt"
hash = "ec967fb3a0371b6fd65721916bcf32b22cf342d6c347ca94814a31820ddd0e1a"

[[files]]
file = "resourcepacks/Mod Menu Helper.zip"
hash = "30cae3d640c7a768890e806908c703db5cd61f3933b5c91985c67f91f82f43a4"

[[files]]
file = "servers.dat"
hash = "775ffd99bfe9e9259bbb49c9c8303197ab8a8053a4501c08917d3f95e1da6f43"
